// <auto-generated />
namespace Itec_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NonRequiredForSubjMess : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NonRequiredForSubjMess));
        
        string IMigrationMetadata.Id
        {
            get { return "201304130712045_NonRequiredForSubjMess"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
